
development:
  adapter: postgresql
  encoding: unicode
  database: hack_news_rails_development
  pool: 5
  username: 
  password:

  
test:
  adapter: postgresql
  encoding: unicode
  database: hack_news_rails_test
  pool: 5
  username: 
  password:


